{{- $root := . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-gigaspaces-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - serviceaccounts
  verbs:
  - get
  - list
{{- if ($root.Values.patchSupport.enabled) }}
- apiGroups:
  - ""
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-gigaspaces-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list