apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: iidr-as
  name: iidr-as
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.iidrAs.resources.requests.storage }}
status: {}
