apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: iidr
  name: iidr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.iidr.resources.requests.storage }}
status: {}
