apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f /Users/anatoliy.berelekhis/IdeaProjects/di-e2e/docker/docker-compose.full.yaml convert -c
    kompose.version: 1.28.0 (HEAD)
  labels:
    io.kompose.service: iidr-as
  name: iidr-as
spec:
  ports:
    - name: "10101"
      port: 10101
      targetPort: 10101
  selector:
    io.kompose.service: iidr-as
status:
  loadBalancer: {}
