apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: iidr-kafka
  name: iidr-kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.iidrKafka.resources.requests.storage }}
status: {}
