# Default values for xap-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: xap-manager
image:
  repository: gigaspaces/smart-cache-enterprise
  tag: 16.3.0
  pullPolicy: IfNotPresent #Always
terminationGracePeriodSeconds: 30

# HA: Define the number of Platform Manager instances (a.k.a replicas) that are deployed.
# HA=true deploys 3 Management Pods, HA=false deploys 1 Management Pod.
ha: false

# license: Define the GigaSpaces XAP licence key.
license: tryme

# Define pod anti-affinity
antiAffinity:
    # enabled: Define whether to deploy and run in affinity mode or anti-affinity mode.
  enabled: false

persistence:
  enabled: false
# service: Define the Platform Manager service configuration.
service:
  # type: Service type.
  type: ClusterIP
  # api: REST Manager API port.
  api:
    enabled: true
    # Changing this value is not supported.
    port: 8090
    nodePort:
  # lus: External LUS port for Space-based remoting
  lus:
    enabled: true
    # Changing this value is not supported.
    port: 4174
    nodePort:
  # lrmi: External LRMI port for Space-based remoting
  lrmi:
    enabled: false
    port: 8200
    nodePort:

nodeSelector:
  enabled: false
  selector:

patchSupport:
  enabled: true

multiCast:
  enabled: false

name:
# hs: Define the Platform Manager headless service configuration.
hs:
  # zkClient: Apache Zookeeper client port. Changing this value is not supported.
  zkClient: 2181
  # zkServer: Apache Zookeeper server port. Changing this value is not supported.
  zkServer: 2888
  # zkLeaderElection: Apache Zookeeper leader election port. Changing this value is not supported.
  zkLeaderElection: 3888
  # lus: Lookup Service port. Changing this value is not supported.
  lus: 4174
# java: Configure the Java options for each Platform Manager instance.
java:
  # heap: Configure the size of the on-heap memory for each Platform Manager instance.
  heap: limit-150Mi
  # options: Configure additional Java options for each Platform Manager instance.
  options:
# resources: Configure the Platform Manager resources.
resources:
  # Best practice is do not specify default resources, so the user can configure them independently.
  # This can be especially risky when the chart is run on an environment with limited
  # resources, such as a minikube. If you still want to configure specific resources, adjust the values as necessary.
  limits:
    memory: 1200Mi

# When enabled, mount metrics configMap for metrics reported by Gigaspaces components.
metrics:
  enabled: true

securityService:
  enabled: true
  port: 9000
  nodePort:
  type: ClusterIP
  ingress:
    enabled: true
  secretKeyRef:
    name: root-credentials
    user: cm9vdA==
    password: cGFzc3dvcmQ=
  rolesConfigMap: roles-map
  readinessProbe:
    initialDelaySeconds: 60
