apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-ui.fullname" . }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "project=mcs,owner=devops"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-ui.selectorLabels" . | nindent 4 }}
