
apiVersion: v1
kind: Service
metadata:
  name: {{ template "xap-dgw.fullname" . }}-hs
  labels:
    app: {{ template "xap-dgw.name" . }}
    chart: {{ template "xap-dgw.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    selectorId: {{ template "xap-dgw.fullname" . }}
