apiVersion: v1
kind: Service
metadata:
  name: {{ template "xap-dgw.fullname" . }}-service
  labels:
    app: {{ template "xap-dgw.name" . }}
    chart: {{ template "xap-dgw.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: jdbc
      protocol: TCP
      port: 5432
  selector:
    selectorId: {{ template "xap-dgw.fullname" . }}-xap-pu 
