tcp:
  8090: "default/xap-manager-service:8090"
  3000: "default/grafana:3000"
  4200: "default/spacedeck:4200"
  8080: "default/redpanda:8080"
  6080: "default/di-manager:6080"
  6081: "default/di-mdm:6081"
  6082: "default/di-subscription-manager-iidr:6082"
  8081: "default/flink-jobmanager:8081"
  5432: "default/xap-dgw-service:5432"
  11701: "default/iidr-kafka:11701"
  10101: "default/iidr-as:10101"
  1521: "default/di-oracledb:1521"
 # 8081: "default/bbw-kafka-producer-svc:8081"
 # 6085: "default/bbw-dih-pc-pluggable-connector:6085"
###################################################################################################
# To configure ingress-controller as Internal LB, uncomment the following depends on your vendor: #
###################################################################################################
### Azure ###

#controller:
#  service:
#    annotations:
#      service.beta.kubernetes.io/azure-load-balancer-internal: true

### AWS ###

controller:
    service:
      external:
        enabled: true
      internal:
        enabled: false
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-internal: "false"
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Owner=owner,Project=project, Name=project-ingress-LB-internal



        
