apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.v3.yaml convert -c
    kompose.version: 1.28.0 (HEAD)
  labels:
    io.kompose.service: di-mdm
  name: di-mdm
spec:
  ports:
    - name: "6081"
      port: 6081
      targetPort: 6081
      protocol: TCP
  selector:
    io.kompose.service: di-mdm
status:
  loadBalancer: {}
