apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: di-manager
  name: di-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: di-manager
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.v3.yaml convert -c
        kompose.version: 1.28.0 (HEAD)
      labels:
        io.kompose.network/docker-di: "true"
        io.kompose.service: di-manager
    spec:
      containers:
        - env:
            - name: MDM_SERVER_FALLBACK-URL
              value: http://di-mdm:6081
            - name: MDM_SERVER_URL
              value: http://di-mdm:6081
          image: {{ .Values.diManager.image.repository }}:{{ .Values.diManager.image.tag }}
          imagePullPolicy: {{ .Values.diMdm.image.pullPolicy }}
{{/*          livenessProbe:*/}}
{{/*            exec:*/}}
{{/*              command:*/}}
{{/*                - curl --fail http://localhost:6080/api/v1/about*/}}
{{/*            failureThreshold: 5*/}}
{{/*            periodSeconds: 10*/}}
{{/*            timeoutSeconds: 1*/}}
          name: di-manager
          ports:
            - containerPort: 6080
          resources: {{ toYaml .Values.diMdm.resources | nindent 12 }}
      restartPolicy: Always
      {{- include "di.imagePullSecrets" . | nindent 6 }}
