#This file is needs to be uploaded to S3 for every change so it accessible through https://resources.gigaspaces.com/helm-values/...

di:
  diMdm:
    resources:
      requests:
        memory: "1000Mi"
        cpu: "1000m"
      limits:
        memory: "2000Mi"
        cpu: "1000m"
  diManager:
    resources:
      requests:
        memory: "1000Mi"
        cpu: "1000m"
      limits:
        memory: "2000Mi"
        cpu: "1000m"
  diOperator:
    resources:
      requests:
        memory: "20Mi"
        cpu: "20m"
      limits:
        memory: "40Mi"
        cpu: "20m"

diSubscriptionManager:
  resources:
    requests:
      memory: "2000Mi"
      cpu: "1000m"
    limits:
      memory: "3000Mi"
      cpu: "1000m"


grafana:
  resources:
    requests:
      memory: "400Mi"
      cpu: "500m"
    limits:
      memory: "800Mi"
      cpu: "1000m"

iidrKafka:
  resources:
    requests:
      memory: "2000Mi"
      cpu: "1000m"
    limits:
      memory: "3000Mi"
      cpu: "1000m"

influxdb:
  resources:
    requests:
      memory: "2000Mi"
      cpu: "500m"
    limits:
      memory: "2000Mi"
      cpu: "1000m"

kafka:
  resources:
    requests:
      memory: "3000Mi"
      cpu: "2000m"
    limits:
      memory: "6000Mi"
      cpu: "2000m"


iidrAS:
  resources:
    requests:
      memory: "400Mi"
      cpu: "500m"
    limits:
      memory: "800Mi"
      cpu: "1000m"

redpanda:
  resources:
    requests:
      memory: "200Mi"
      cpu: "20m"
    limits:
      memory: "200Mi"
      cpu: "40m"


spacedeck:
  resources:
    requests:
      memory: "1000Mi"
      cpu: "1000m"
    limits:
      memory: "2000Mi"
      cpu: "1000m"


manager:
  resources:
    requests:
      memory: "2000Mi"
      cpu: "1000m"
    limits:
      memory: "2400Mi"
      cpu: "2000m"

operator:
  resources:
    requests:
      memory: "2000Mi"
      cpu: "1000m"
    limits:
      memory: "2400Mi"
      cpu: "2000m"

service-creator:
  resources:
    requests:
      memory: "2000Mi"
      cpu: "1000m"
    limits:
      memory: "2400Mi"
      cpu: "2000m"

service-operator:
  resources:
    requests:
      memory: "2000Mi"
      cpu: "1000m"
    limits:
      memory: "2400Mi"
      cpu: "2000m"