#This file is needs to be uploaded to S3 for every change so it accessible through https://resources.gigaspaces.com/helm-values/...
di:
  diMdm:
    resources:
      requests:
        memory: "500Mi"
        cpu: "500m"
      limits:
        memory: "1000Mi"
        cpu: "500m"
  diManager:
    resources:
      requests:
        memory: "500Mi"
        cpu: "500m"
      limits:
        memory: "1000Mi"
        cpu: "500m"
  diOperator:
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
      limits:
        memory: "20Mi"
        cpu: "10m"

diSubscriptionManager:
  resources:
    requests:
      memory: "1000Mi"
      cpu: "500m"
    limits:
      memory: "1500Mi"
      cpu: "500m"


grafana:
  resources:
    requests:
      memory: "200Mi"
      cpu: "250m"
    limits:
      memory: "400Mi"
      cpu: "500m"

iidrKafka:
  resources:
    requests:
      memory: "1000Mi"
      cpu: "500m"
    limits:
      memory: "1500Mi"
      cpu: "500m"

influxdb:
  resources:
    requests:
      memory: "1000Mi"
      cpu: "250m"
    limits:
      memory: "1000Mi"
      cpu: "500m"

kafka:
  resources:
    requests:
      memory: "1500Mi"
      cpu: "1000m"
    limits:
      memory: "3000Mi"
      cpu: "1000m"


iidrAS:
  resources:
    requests:
      memory: "200Mi"
      cpu: "250m"
    limits:
      memory: "400Mi"
      cpu: "500m"

redpanda:
  resources:
    requests:
      memory: "100Mi"
      cpu: "10m"
    limits:
      memory: "100Mi"
      cpu: "20m"


spacedeck:
  resources:
    requests:
      memory: "500Mi"
      cpu: "500m"
    limits:
      memory: "1000Mi"
      cpu: "500m"


manager:
  resources:
    requests:
      memory: "1000Mi"
      cpu: "500m"
    limits:
      memory: "1200Mi"
      cpu: "1000m"

operator:
  resources:
    requests:
      memory: "1000Mi"
      cpu: "500m"
    limits:
      memory: "1200Mi"
      cpu: "1000m"

service-creator:
  resources:
    requests:
      memory: "1000Mi"
      cpu: "500m"
    limits:
      memory: "1200Mi"
      cpu: "1000m"

service-operator:
  resources:
    requests:
      memory: "1000Mi"
      cpu: "500m"
    limits:
      memory: "1200Mi"
      cpu: "1000m"